from __future__ import annotations

from typing import Any, Generic, Literal, TypeVar, overload
from typing_extensions import LiteralString

from planframe.backend.adapter import BackendAdapter
from planframe.expr.api import Expr
from planframe.groupby import GroupedFrame
from planframe.plan.nodes import PlanNode
from planframe.schema.ir import Schema
from planframe.typing._schema_types import JoinedSchema

SchemaT = TypeVar("SchemaT")
BackendFrameT = TypeVar("BackendFrameT")
BackendExprT = TypeVar("BackendExprT")
OtherSchemaT = TypeVar("OtherSchemaT")
T = TypeVar("T")


class Frame(Generic[SchemaT, BackendFrameT, BackendExprT]):
    _data: BackendFrameT
    _adapter: BackendAdapter[BackendFrameT, BackendExprT]
    _plan: PlanNode
    _schema: Schema

    @classmethod
    def source(
        cls,
        data: BackendFrameT,
        *,
        adapter: BackendAdapter[BackendFrameT, BackendExprT],
        schema: type[SchemaT],
    ) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...

    def schema(self) -> Schema: ...
    def plan(self) -> PlanNode: ...

    # NOTE: Pyright's behavior around LiteralString vs str can be permissive.
    # Overloads here are intended to encourage literal call sites and improve IDE help.
    @overload
    def select(self, __c1: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def select(self, __c1: LiteralString, __c2: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def select(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def select(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString, __c4: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def select(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString, __c4: LiteralString, __c5: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def select(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString, __c4: LiteralString, __c5: LiteralString, __c6: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def select(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString, __c4: LiteralString, __c5: LiteralString, __c6: LiteralString, __c7: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def select(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString, __c4: LiteralString, __c5: LiteralString, __c6: LiteralString, __c7: LiteralString, __c8: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def select(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString, __c4: LiteralString, __c5: LiteralString, __c6: LiteralString, __c7: LiteralString, __c8: LiteralString, __c9: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def select(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString, __c4: LiteralString, __c5: LiteralString, __c6: LiteralString, __c7: LiteralString, __c8: LiteralString, __c9: LiteralString, __c10: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    def select(self, *columns: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...

    def select_prefix(self, prefix: str) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    def select_suffix(self, suffix: str) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    def select_regex(self, pattern: str) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...

    @overload
    def select_exclude(self, __c1: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def select_exclude(self, __c1: LiteralString, __c2: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def select_exclude(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def select_exclude(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString, __c4: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def select_exclude(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString, __c4: LiteralString, __c5: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def select_exclude(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString, __c4: LiteralString, __c5: LiteralString, __c6: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def select_exclude(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString, __c4: LiteralString, __c5: LiteralString, __c6: LiteralString, __c7: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def select_exclude(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString, __c4: LiteralString, __c5: LiteralString, __c6: LiteralString, __c7: LiteralString, __c8: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def select_exclude(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString, __c4: LiteralString, __c5: LiteralString, __c6: LiteralString, __c7: LiteralString, __c8: LiteralString, __c9: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def select_exclude(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString, __c4: LiteralString, __c5: LiteralString, __c6: LiteralString, __c7: LiteralString, __c8: LiteralString, __c9: LiteralString, __c10: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    def select_exclude(self, *columns: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...

    @overload
    def drop(self, __c1: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def drop(self, __c1: LiteralString, __c2: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def drop(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def drop(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString, __c4: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def drop(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString, __c4: LiteralString, __c5: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def drop(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString, __c4: LiteralString, __c5: LiteralString, __c6: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def drop(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString, __c4: LiteralString, __c5: LiteralString, __c6: LiteralString, __c7: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def drop(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString, __c4: LiteralString, __c5: LiteralString, __c6: LiteralString, __c7: LiteralString, __c8: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def drop(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString, __c4: LiteralString, __c5: LiteralString, __c6: LiteralString, __c7: LiteralString, __c8: LiteralString, __c9: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def drop(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString, __c4: LiteralString, __c5: LiteralString, __c6: LiteralString, __c7: LiteralString, __c8: LiteralString, __c9: LiteralString, __c10: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    def drop(self, *columns: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...

    def drop_prefix(self, prefix: str) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    def drop_suffix(self, suffix: str) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    def drop_regex(self, pattern: str) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...

    @overload
    def reorder_columns(self, __c1: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def reorder_columns(self, __c1: LiteralString, __c2: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def reorder_columns(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def reorder_columns(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString, __c4: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def reorder_columns(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString, __c4: LiteralString, __c5: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def reorder_columns(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString, __c4: LiteralString, __c5: LiteralString, __c6: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def reorder_columns(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString, __c4: LiteralString, __c5: LiteralString, __c6: LiteralString, __c7: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def reorder_columns(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString, __c4: LiteralString, __c5: LiteralString, __c6: LiteralString, __c7: LiteralString, __c8: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def reorder_columns(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString, __c4: LiteralString, __c5: LiteralString, __c6: LiteralString, __c7: LiteralString, __c8: LiteralString, __c9: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def reorder_columns(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString, __c4: LiteralString, __c5: LiteralString, __c6: LiteralString, __c7: LiteralString, __c8: LiteralString, __c9: LiteralString, __c10: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    def reorder_columns(self, *columns: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...

    @overload
    def select_first(self, __c1: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def select_first(self, __c1: LiteralString, __c2: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def select_first(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def select_first(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString, __c4: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def select_first(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString, __c4: LiteralString, __c5: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def select_first(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString, __c4: LiteralString, __c5: LiteralString, __c6: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def select_first(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString, __c4: LiteralString, __c5: LiteralString, __c6: LiteralString, __c7: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def select_first(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString, __c4: LiteralString, __c5: LiteralString, __c6: LiteralString, __c7: LiteralString, __c8: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def select_first(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString, __c4: LiteralString, __c5: LiteralString, __c6: LiteralString, __c7: LiteralString, __c8: LiteralString, __c9: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def select_first(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString, __c4: LiteralString, __c5: LiteralString, __c6: LiteralString, __c7: LiteralString, __c8: LiteralString, __c9: LiteralString, __c10: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    def select_first(self, *columns: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...

    @overload
    def select_last(self, __c1: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def select_last(self, __c1: LiteralString, __c2: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def select_last(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def select_last(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString, __c4: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def select_last(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString, __c4: LiteralString, __c5: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def select_last(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString, __c4: LiteralString, __c5: LiteralString, __c6: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def select_last(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString, __c4: LiteralString, __c5: LiteralString, __c6: LiteralString, __c7: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def select_last(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString, __c4: LiteralString, __c5: LiteralString, __c6: LiteralString, __c7: LiteralString, __c8: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def select_last(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString, __c4: LiteralString, __c5: LiteralString, __c6: LiteralString, __c7: LiteralString, __c8: LiteralString, __c9: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def select_last(self, __c1: LiteralString, __c2: LiteralString, __c3: LiteralString, __c4: LiteralString, __c5: LiteralString, __c6: LiteralString, __c7: LiteralString, __c8: LiteralString, __c9: LiteralString, __c10: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    def select_last(self, *columns: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...

    def move(
        self,
        column: LiteralString,
        *,
        before: LiteralString | None = ...,
        after: LiteralString | None = ...,
    ) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...

    def rename(self, **mapping: str) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...

    def rename_prefix(self, prefix: str, *subset: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    def rename_suffix(self, suffix: str, *subset: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    def rename_replace(self, old: str, new: str, *subset: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...

    def with_column(
        self,
        name: LiteralString,
        expr: Expr[T],
    ) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...

    @overload
    def cast(self, name: LiteralString, dtype: type[T]) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    @overload
    def cast(self, name: LiteralString, dtype: Any) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    def filter(self, predicate: Expr[bool]) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    def sort(self, *columns: LiteralString, descending: bool = ...) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    def unique(
        self,
        *subset: LiteralString,
        keep: Literal["first", "last"] = ...,
    ) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    def duplicated(
        self,
        *subset: LiteralString,
        keep: Literal["first", "last"] | bool = ...,
        out_name: str = ...,
    ) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    def group_by(self, *keys: LiteralString) -> GroupedFrame[SchemaT, BackendFrameT, BackendExprT]: ...
    def drop_nulls(self, *subset: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    def fill_null(self, value: Any, *subset: LiteralString) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    def melt(
        self,
        *,
        id_vars: tuple[LiteralString, ...],
        value_vars: tuple[LiteralString, ...],
        variable_name: str = ...,
        value_name: str = ...,
    ) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...

    def slice(self, offset: int, length: int | None = ...) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    def limit(self, n: int) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    def head(self, n: int) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    def tail(self, n: int) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    def concat_vertical(self, other: Frame[SchemaT, BackendFrameT, BackendExprT]) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...
    def pivot(
        self,
        *,
        index: tuple[LiteralString, ...],
        on: LiteralString,
        values: LiteralString,
        agg: Literal["first", "last", "sum", "mean", "min", "max", "count", "len", "median"] = ...,
        on_columns: tuple[str, ...] | None = ...,
        separator: str = ...,
    ) -> Frame[SchemaT, BackendFrameT, BackendExprT]: ...

    @overload
    def join(
        self,
        other: Frame[OtherSchemaT, BackendFrameT, BackendExprT],
        *,
        on: tuple[LiteralString],
        how: Literal["inner", "left", "right", "full", "semi", "anti", "cross"] = ...,
        suffix: str = ...,
    ) -> Frame[JoinedSchema[SchemaT, OtherSchemaT], BackendFrameT, BackendExprT]: ...
    @overload
    def join(
        self,
        other: Frame[OtherSchemaT, BackendFrameT, BackendExprT],
        *,
        on: tuple[LiteralString, LiteralString],
        how: Literal["inner", "left", "right", "full", "semi", "anti", "cross"] = ...,
        suffix: str = ...,
    ) -> Frame[JoinedSchema[SchemaT, OtherSchemaT], BackendFrameT, BackendExprT]: ...
    @overload
    def join(
        self,
        other: Frame[OtherSchemaT, BackendFrameT, BackendExprT],
        *,
        on: tuple[LiteralString, LiteralString, LiteralString],
        how: Literal["inner", "left", "right", "full", "semi", "anti", "cross"] = ...,
        suffix: str = ...,
    ) -> Frame[JoinedSchema[SchemaT, OtherSchemaT], BackendFrameT, BackendExprT]: ...
    @overload
    def join(
        self,
        other: Frame[OtherSchemaT, BackendFrameT, BackendExprT],
        *,
        on: tuple[LiteralString, LiteralString, LiteralString, LiteralString],
        how: Literal["inner", "left", "right", "full", "semi", "anti", "cross"] = ...,
        suffix: str = ...,
    ) -> Frame[JoinedSchema[SchemaT, OtherSchemaT], BackendFrameT, BackendExprT]: ...
    @overload
    def join(
        self,
        other: Frame[OtherSchemaT, BackendFrameT, BackendExprT],
        *,
        on: tuple[LiteralString, LiteralString, LiteralString, LiteralString, LiteralString],
        how: Literal["inner", "left", "right", "full", "semi", "anti", "cross"] = ...,
        suffix: str = ...,
    ) -> Frame[JoinedSchema[SchemaT, OtherSchemaT], BackendFrameT, BackendExprT]: ...
    def collect(self) -> BackendFrameT: ...

    def materialize_model(
        self,
        name: str,
        *,
        kind: Literal["dataclass", "pydantic"] = ...,
    ) -> type[Any]: ...
